name: Push To Kyso
on: 
  push:
    branches:
      - master
jobs:
  Push-To-Kyso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g kyso
      - run: kyso login --kysoInstallUrl https://kyso.io --provider kyso --username kyle@kyso.io --token 06ba92bf-fa86-45c9-9323-709af28c7051
      - run: kyso push
