name: Push To Kyso
on:
  push:
    branches:
      - main
jobs:
  Push-To-Kyso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g kyso
      - run: kyso login --kysoInstallUrl https://kyso.io --provider kyso --username kyle@kyso.io --token 3247b46a-1582-45c0-afa1-4d1540d54d9c
      - run: kyso push
